ifndef::imagesdir[:imagesdir: doc]
Zamia AI Installation and First Steps
=====================================

These are generic installation instructions aimed at technical users and developers
who want to run Zamia AI on GNU/Linux (and similar) systems.

We assume that you want to install Zamia AI as a non-root user in a directory in your
home directory: `~/zamia-ai`. It should be straightforward to adapt these instructions to install
Zamia AI in a different directory inside or outside of your home where you have write permissions
or in a system-wide location like `/usr/local/zamia-ai` or `/opt/zamia-ai` (which then may require
root permissions at some point).

[source,bash]
----
mkdir ~/zamia-ai
cd ~/zamia-ai
----

Requirements
------------

We assume the following packages are installed on your OS:

* Python 2.7 with pip, cython, swig
* tensorflow
* SQLite, python-sqlite 
* libatlas, zlib, libpulse 
* pkg-config, git, gcc, automake, autoconf, libtoolize, subversion, eSpeak NG 
* XSB dependencies: libcurl, libpcre, makedepend, dos2unix

If you want to install all on these on Debian, run (as root):

[source,bash]
----
pip install tensorflow
apt-get install cython swig python-sqlite libatlas-dev libatlas3-base pkg-config git zlib1g-dev automake autoconf libtool subversion libpulse-dev libcurl4-openssl-dev libpcre3-dev xutils-dev dos2unix espeak-ng
----

XSB Prolog with Python Bindings
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Download the latest XSB tarball from https://sourceforge.net/projects/xsb/

`py-xsb-prolog` needs the XSB dynamic library to work: First, follow the standard XSB build instructions:

[source,bash]
----
tar xfvz XSB38.tar.gz 
cd XSB/build
./configure
./makexsb 
----

in order to build `libxsb.so`, execute these commands:

[source,bash]
----
./makexsb dynmodule
cat >>~/.bashrc <<EOF
export LD_LIBRARY_PATH="\${HOME}/zamia-ai/XSB/config/x86_64-unknown-linux-gnu/bin:\$LD_LIBRARY_PATH"
EOF
source ~/.bashrc
----

now, we can install the prolog bindings:

[source,bash]
----
pip install --user py-xsb-prolog
----

Kaldi ASR with Python Bindings
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Clone the latest Kaldi ASR sources from gibthub, follow the regular build instructions:
[source,bash]
----
cd ~/zamia-ai/
git clone https://github.com/kaldi-asr/kaldi.git
cd kaldi/tools
make
cd ../src
./configure --shared
make depend
make
----

next, we need to create a package-config file which describes where Kaldi ASR is installed:
[source,bash]
----
cd ~/zamia-ai/kaldi
mkdir pkgconfig
cat >pkgconfig/kaldi-asr.pc <<EOF
kaldi_root=/home/bofh/zamia-ai/kaldi

Name: kaldi-asr
Description: kaldi-asr speech recognition toolkit
Version: 5.2
Libs: -L\${kaldi_root}/tools/openfst/lib -L\${kaldi_root}/src/lib -lkaldi-decoder -lkaldi-lat -lkaldi-fstext -lkaldi-hmm -lkaldi-feat -lkaldi-transform -lkaldi-gmm -lkaldi-tree -lkaldi-util -lkaldi-matrix -lkaldi-base -lkaldi-nnet3 -lkaldi-online2
Cflags: -I\${kaldi_root}/src  -I\${kaldi_root}/tools/openfst/include
EOF
echo 'export PKG_CONFIG_PATH="\${HOME}/zamia-ai/kaldi/pkgconfig:\${PKG_CONFIG_PATH}"' >>~/.bashrc
source ~/.bashrc
----

finally, we can install the Kaldi ASR python wrapper:
[source,bash]
----
pip install --user py-kaldi-asr
----

Other Python Dependencies
~~~~~~~~~~~~~~~~~~~~~~~~~

Install the python modules Zamia AI depends on:

[source,bash]
----
pip install --user py-nltools cmdln pytz tzlocal scipy sqlalchemy codegen
----

Zamia AI
--------

Clone the Zamia AI sources from GitHub:
[source,bash]
----
cd ~/zamia-ai
git clone https://github.com/gooofy/zamia-ai.git
----

create a file called `~/.airc`:
```ini
[db]
url                 = sqlite:///ai.db

[semantics]
toplevel            = chatbot
server_host         = localhost
server_port         = 8302

xsb_root            = /home/bofh/zamia-ai/XSB

[weather]
api_key             = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
city_id             = 2825297
city_pred           = stuttgart

[context]
place               = 'http://www.wikidata.org/entity/Q1022'
channel             = 'http://www.wikidata.org/entity/Q795291'
time                = today
```

(you need an OpenWeatherMap API Key for the weather module to work - otherwise leave it blank)

now it is time to compile the knowledge base:

[source,bash]
----
cd ~/zamia-ai
./ai_cli.py compile all
----

and train your first model:

[source,bash]
----
mkdir models
cat >models/en_3_512.ini <<EOF
[training]

lang                       = en
batch_size                 = 32

# Optimizer for training: (adadelta, adam, rmsprop)
optimizer                  = adam

# Learning rate
learning_rate              = 0.0002

# Clip gradients to this norm
max_gradient_norm          = 1.0

[model]

# RNN cell for encoder and decoder, default: lstm
cell_type                  = lstm  

# Attention mechanism: (bahdanau, luong), default: bahdanau
attention_type             = bahdanau

# Number of hidden units in each layer
hidden_units               = 512

# Number of layers in each encoder and decoder
depth                      = 3

# Embedding dimensions of encoder and decoder inputs
embedding_size             = 500

# Use residual connection between layers
use_residual               = True

# Use input feeding method in attentional decoder
attn_input_feeding         = False

# Use dropout in each rnn cell
use_dropout                = True

# Dropout probability for input/output/state units (0.0: no dropout)
dropout_rate               = 0.3

# Use half precision float16 instead of float32 as dtype
use_fp16                   = False

[decode]
beam_width                 = 12
max_decode_step            = 500
EOF

./ai_cli.py train models/en_3_512.ini -n 10000
----

alternatively, you can download a pre-built model here: http://goofy.zamia.org/zamia-ai/

chat with the model:
```bash
[guenter@dagobert zamia-ai]$ ./ai_cli.py chat -m models/en_3_512.ini chatbot
[xsb_configuration loaded]

...

INFO:root:model restored from models/en_3_512/latest.ckpt
ai> hello computer
INFO:root:RESP: [   0.0] Hi! 
ai> how are you?
INFO:root:RESP: [   0.0] Great, thanks. How do you feel today? 
ai> I am well
INFO:root:RESP: [   0.0] Excellent! 
ai> what is 2 times 2
INFO:root:RESP: [ 104.0] 4 
ai> correct
INFO:root:RESP: [   0.0] Good. 
ai> where do you live?
INFO:root:RESP: [ 100.0] I am located in Stuttgart. 
ai> what is your favorite movie?
INFO:root:RESP: [ 100.0] 2001: A Space Odyssey by Stanley Kubrick 
ai> How about the weather?
INFO:root:RESP: [   2.0] today there will be some clouds in Stuttgart with temperatures between 1 and 7 degrees. 
ai> Tell me something about yourself
INFO:root:RESP: [   0.0] Please tell me how I can help you. 
ai> Where was Stephen King born?
INFO:root:RESP: [   4.0] Stephen King was born in Portland, I think. 
```

