% prolog

%
% a bit of math (very crude so far, but we have to get started somewhere...)
%

transcribe_number(en, nominative,  0, "zero").
transcribe_number(en, nominative,  1, "one").
transcribe_number(en, nominative,  2, "two").
transcribe_number(en, nominative,  3, "three").
transcribe_number(en, nominative,  4, "four").
transcribe_number(en, nominative,  5, "five").
transcribe_number(en, nominative,  6, "six").
transcribe_number(en, nominative,  7, "seven").
transcribe_number(en, nominative,  8, "eight").
transcribe_number(en, nominative,  9, "nine").
transcribe_number(en, nominative, 10, "ten").
transcribe_number(en, nominative, 11, "eleven").
transcribe_number(en, nominative, 12, "twelve").
transcribe_number(en, nominative, 13, "thirteen").
transcribe_number(en, nominative, 14, "fourteen").
transcribe_number(en, nominative, 15, "fifteen").
transcribe_number(en, nominative, 16, "sixteen").
transcribe_number(en, nominative, 17, "seventeen").
transcribe_number(en, nominative, 18, "eighteen").
transcribe_number(en, nominative, 19, "nineteen").
transcribe_number(en, nominative, 20, "twenty").
transcribe_number(en, nominative, 21, "twenty-one").
transcribe_number(en, nominative, 22, "twenty-two").
transcribe_number(en, nominative, 23, "twenty-three").
transcribe_number(en, nominative, 24, "twenty-four").
transcribe_number(en, nominative, 25, "twenty-five").
transcribe_number(en, nominative, 26, "twenty-six").
transcribe_number(en, nominative, 27, "twenty-seven").
transcribe_number(en, nominative, 28, "twenty-eight").
transcribe_number(en, nominative, 29, "twenty-nine").
transcribe_number(en, nominative, 30, "thirty").
transcribe_number(en, nominative, 31, "thirty-one").
transcribe_number(en, nominative, 32, "thirty-two").
transcribe_number(en, nominative, 33, "thirty-three").
transcribe_number(en, nominative, 34, "thirty-four").
transcribe_number(en, nominative, 35, "thirty-five").
transcribe_number(en, nominative, 36, "thirty-six").
transcribe_number(en, nominative, 37, "thirty-seven").
transcribe_number(en, nominative, 38, "thirty-eight").
transcribe_number(en, nominative, 39, "thirty-nine").
transcribe_number(en, nominative, 40, "forty").
transcribe_number(en, nominative, 41, "forty-one").
transcribe_number(en, nominative, 42, "forty-two").
transcribe_number(en, nominative, 43, "forty-three").
transcribe_number(en, nominative, 44, "forty-four").
transcribe_number(en, nominative, 45, "forty-five").
transcribe_number(en, nominative, 46, "forty-six").
transcribe_number(en, nominative, 47, "forty-seven").
transcribe_number(en, nominative, 48, "forty-eight").
transcribe_number(en, nominative, 49, "forty-nine").
transcribe_number(en, nominative, 50, "fifty").
transcribe_number(en, nominative, 51, "fifty-one").
transcribe_number(en, nominative, 52, "fifty-two").
transcribe_number(en, nominative, 53, "fifty-three").
transcribe_number(en, nominative, 54, "fifty-four").
transcribe_number(en, nominative, 55, "fifty-five").
transcribe_number(en, nominative, 56, "fifty-six").
transcribe_number(en, nominative, 57, "fifty-seven").
transcribe_number(en, nominative, 58, "fifty-eight").
transcribe_number(en, nominative, 59, "fifty-nine").
transcribe_number(en, nominative, 60, "sixty").
transcribe_number(en, nominative, 61, "sixty-one").
transcribe_number(en, nominative, 62, "sixty-two").
transcribe_number(en, nominative, 63, "sixty-three").
transcribe_number(en, nominative, 64, "sixty-four").
transcribe_number(en, nominative, 65, "sixty-five").
transcribe_number(en, nominative, 66, "sixty-six").
transcribe_number(en, nominative, 67, "sixty-seven").
transcribe_number(en, nominative, 68, "sixty-eight").
transcribe_number(en, nominative, 69, "sixty-nine").
transcribe_number(en, nominative, 70, "seventy").
transcribe_number(en, nominative, 71, "seventy-one").
transcribe_number(en, nominative, 72, "seventy-two").
transcribe_number(en, nominative, 73, "seventy-three").
transcribe_number(en, nominative, 74, "seventy-four").
transcribe_number(en, nominative, 75, "seventy-five").
transcribe_number(en, nominative, 76, "seventy-six").
transcribe_number(en, nominative, 77, "seventy-seven").
transcribe_number(en, nominative, 78, "seventy-eight").
transcribe_number(en, nominative, 79, "seventy-nine").
transcribe_number(en, nominative, 80, "eighty").
transcribe_number(en, nominative, 81, "eighty-one").
transcribe_number(en, nominative, 82, "eighty-two").
transcribe_number(en, nominative, 83, "eighty-three").
transcribe_number(en, nominative, 84, "eighty-four").
transcribe_number(en, nominative, 85, "eighty-five").
transcribe_number(en, nominative, 86, "eighty-six").
transcribe_number(en, nominative, 87, "eighty-seven").
transcribe_number(en, nominative, 88, "eighty-eight").
transcribe_number(en, nominative, 89, "eighty-nine").
transcribe_number(en, nominative, 90, "ninety").
transcribe_number(en, nominative, 91, "ninety-one").
transcribe_number(en, nominative, 92, "ninety-two").
transcribe_number(en, nominative, 93, "ninety-three").
transcribe_number(en, nominative, 94, "ninety-four").
transcribe_number(en, nominative, 95, "ninety-five").
transcribe_number(en, nominative, 96, "ninety-six").
transcribe_number(en, nominative, 97, "ninety-seven").
transcribe_number(en, nominative, 98, "ninety-eight").
transcribe_number(en, nominative, 99, "ninety-nine").
transcribe_number(en, nominative, 100, "one hundred").

transcribe_number(en, ordinal,  0, "zeroth").
transcribe_number(en, ordinal,  1, "first").
transcribe_number(en, ordinal,  2, "second").
transcribe_number(en, ordinal,  3, "third").
transcribe_number(en, ordinal,  4, "fourth").
transcribe_number(en, ordinal,  5, "fifth").
transcribe_number(en, ordinal,  6, "sixth").
transcribe_number(en, ordinal,  7, "seventh").
transcribe_number(en, ordinal,  8, "eighth").
transcribe_number(en, ordinal,  9, "ninth").
transcribe_number(en, ordinal, 10, "tenth").
transcribe_number(en, ordinal, 11, "eleventh").
transcribe_number(en, ordinal, 12, "twelfth").
transcribe_number(en, ordinal, 13, "thirteenth").
transcribe_number(en, ordinal, 14, "fourteenth").
transcribe_number(en, ordinal, 15, "fifteenth").
transcribe_number(en, ordinal, 16, "sixteenth").
transcribe_number(en, ordinal, 17, "seventeenth").
transcribe_number(en, ordinal, 18, "eighteenth").
transcribe_number(en, ordinal, 19, "nineteenth").
transcribe_number(en, ordinal, 20, "twentieth").
transcribe_number(en, ordinal, 21, "twenty-first").
transcribe_number(en, ordinal, 22, "twenty-second").
transcribe_number(en, ordinal, 23, "twenty-third").
transcribe_number(en, ordinal, 24, "twenty-fourth").
transcribe_number(en, ordinal, 25, "twenty-fifth").
transcribe_number(en, ordinal, 26, "twenty-sixth").
transcribe_number(en, ordinal, 27, "twenty-seventh").
transcribe_number(en, ordinal, 28, "twenty-eighth").
transcribe_number(en, ordinal, 29, "twenty-ninth").
transcribe_number(en, ordinal, 30, "thirtieth").
transcribe_number(en, ordinal, 31, "thirty-first").
transcribe_number(en, ordinal, 32, "thirty-second").
transcribe_number(en, ordinal, 33, "thirty-third").
transcribe_number(en, ordinal, 34, "thirty-fourth").
transcribe_number(en, ordinal, 35, "thirty-fifth").
transcribe_number(en, ordinal, 36, "thirty-sixth").
transcribe_number(en, ordinal, 37, "thirty-seventh").
transcribe_number(en, ordinal, 38, "thirty-eighth").
transcribe_number(en, ordinal, 39, "thirty-ninth").
transcribe_number(en, ordinal, 40, "fortieth").
transcribe_number(en, ordinal, 41, "forty-first").
transcribe_number(en, ordinal, 42, "forty-second").
transcribe_number(en, ordinal, 43, "forty-third").
transcribe_number(en, ordinal, 44, "forty-fourth").
transcribe_number(en, ordinal, 45, "forty-fifth").
transcribe_number(en, ordinal, 46, "forty-sixth").
transcribe_number(en, ordinal, 47, "forty-seventh").
transcribe_number(en, ordinal, 48, "forty-eighth").
transcribe_number(en, ordinal, 49, "forty-ninth").
transcribe_number(en, ordinal, 50, "fiftieth").
transcribe_number(en, ordinal, 51, "fifty-first").
transcribe_number(en, ordinal, 52, "fifty-second").
transcribe_number(en, ordinal, 53, "fifty-third").
transcribe_number(en, ordinal, 54, "fifty-fourth").
transcribe_number(en, ordinal, 55, "fifty-fifth").
transcribe_number(en, ordinal, 56, "fifty-sixth").
transcribe_number(en, ordinal, 57, "fifty-seventh").
transcribe_number(en, ordinal, 58, "fifty-eighth").
transcribe_number(en, ordinal, 59, "fifty-ninth").
transcribe_number(en, ordinal, 60, "sixtieth").
transcribe_number(en, ordinal, 61, "sixty-first").
transcribe_number(en, ordinal, 62, "sixty-second").
transcribe_number(en, ordinal, 63, "sixty-third").
transcribe_number(en, ordinal, 64, "sixty-fourth").
transcribe_number(en, ordinal, 65, "sixty-fifth").
transcribe_number(en, ordinal, 66, "sixty-sixth").
transcribe_number(en, ordinal, 67, "sixty-seventh").
transcribe_number(en, ordinal, 68, "sixty-eighth").
transcribe_number(en, ordinal, 69, "sixty-ninth").
transcribe_number(en, ordinal, 70, "seventieth").
transcribe_number(en, ordinal, 71, "seventy-first").
transcribe_number(en, ordinal, 72, "seventy-second").
transcribe_number(en, ordinal, 73, "seventy-third").
transcribe_number(en, ordinal, 74, "seventy-fourth").
transcribe_number(en, ordinal, 75, "seventy-fifth").
transcribe_number(en, ordinal, 76, "seventy-sixth").
transcribe_number(en, ordinal, 77, "seventy-seventh").
transcribe_number(en, ordinal, 78, "seventy-eighth").
transcribe_number(en, ordinal, 79, "seventy-ninth").
transcribe_number(en, ordinal, 80, "eightieth").
transcribe_number(en, ordinal, 81, "eighty-first").
transcribe_number(en, ordinal, 82, "eighty-second").
transcribe_number(en, ordinal, 83, "eighty-third").
transcribe_number(en, ordinal, 84, "eighty-fourth").
transcribe_number(en, ordinal, 85, "eighty-fifth").
transcribe_number(en, ordinal, 86, "eighty-sixth").
transcribe_number(en, ordinal, 87, "eighty-seventh").
transcribe_number(en, ordinal, 88, "eighty-eighth").
transcribe_number(en, ordinal, 89, "eighty-ninth").
transcribe_number(en, ordinal, 90, "ninetieth").
transcribe_number(en, ordinal, 91, "ninety-first").
transcribe_number(en, ordinal, 92, "ninety-second").
transcribe_number(en, ordinal, 93, "ninety-third").
transcribe_number(en, ordinal, 94, "ninety-fourth").
transcribe_number(en, ordinal, 95, "ninety-fifth").
transcribe_number(en, ordinal, 96, "ninety-sixth").
transcribe_number(en, ordinal, 97, "ninety-seventh").
transcribe_number(en, ordinal, 98, "ninety-eighth").
transcribe_number(en, ordinal, 99, "ninety-ninth").
transcribe_number(en, ordinal, 100, "one hundredth").

transcribe_number(de, nominative,  0, "null").
transcribe_number(de, nominative,  1, "eins").
transcribe_number(de, nominative,  2, "zwei").
transcribe_number(de, nominative,  3, "drei").
transcribe_number(de, nominative,  4, "vier").
transcribe_number(de, nominative,  5, "fünf").
transcribe_number(de, nominative,  6, "sechs").
transcribe_number(de, nominative,  7, "sieben").
transcribe_number(de, nominative,  8, "acht").
transcribe_number(de, nominative,  9, "neun").
transcribe_number(de, nominative, 10, "zehn").
transcribe_number(de, nominative, 11, "elf").
transcribe_number(de, nominative, 12, "zwölf").
transcribe_number(de, nominative, 13, "dreizehn").
transcribe_number(de, nominative, 14, "vierzehn").
transcribe_number(de, nominative, 15, "fünfzehn").
transcribe_number(de, nominative, 16, "sechzehn").
transcribe_number(de, nominative, 17, "siebzehn").
transcribe_number(de, nominative, 18, "achtzehn").
transcribe_number(de, nominative, 19, "neunzehn").
transcribe_number(de, nominative, 20, "zwanzig").
transcribe_number(de, nominative, 21, "einundzwanzig").
transcribe_number(de, nominative, 22, "zweiundzwanzig").
transcribe_number(de, nominative, 23, "dreiundzwanzig").
transcribe_number(de, nominative, 24, "vierundzwanzig").
transcribe_number(de, nominative, 25, "fünfundzwanzig").
transcribe_number(de, nominative, 26, "sechsundzwanzig").
transcribe_number(de, nominative, 27, "siebenundzwanzig").
transcribe_number(de, nominative, 28, "achtundzwanzig").
transcribe_number(de, nominative, 29, "neunundzwanzig").
transcribe_number(de, nominative, 30, "dreißig").
transcribe_number(de, nominative, 31, "einunddreißig").
transcribe_number(de, nominative, 32, "zweiunddreißig").
transcribe_number(de, nominative, 33, "dreiunddreißig").
transcribe_number(de, nominative, 34, "vierunddreißig").
transcribe_number(de, nominative, 35, "fünfunddreißig").
transcribe_number(de, nominative, 36, "sechsunddreißig").
transcribe_number(de, nominative, 37, "siebenunddreißig").
transcribe_number(de, nominative, 38, "achtunddreißig").
transcribe_number(de, nominative, 39, "neununddreißig").
transcribe_number(de, nominative, 40, "vierzig").
transcribe_number(de, nominative, 41, "einundvierzig").
transcribe_number(de, nominative, 42, "zweiundvierzig").
transcribe_number(de, nominative, 43, "dreiundvierzig").
transcribe_number(de, nominative, 44, "vierundvierzig").
transcribe_number(de, nominative, 45, "fünfundvierzig").
transcribe_number(de, nominative, 46, "sechsundvierzig").
transcribe_number(de, nominative, 47, "siebenundvierzig").
transcribe_number(de, nominative, 48, "achtundvierzig").
transcribe_number(de, nominative, 49, "neunundvierzig").
transcribe_number(de, nominative, 50, "fünfzig").
transcribe_number(de, nominative, 51, "einundfünfzig").
transcribe_number(de, nominative, 52, "zweiundfünfzig").
transcribe_number(de, nominative, 53, "dreiundfünfzig").
transcribe_number(de, nominative, 54, "vierundfünfzig").
transcribe_number(de, nominative, 55, "fünfundfünfzig").
transcribe_number(de, nominative, 56, "sechsundfünfzig").
transcribe_number(de, nominative, 57, "siebenundfünfzig").
transcribe_number(de, nominative, 58, "achtundfünfzig").
transcribe_number(de, nominative, 59, "neunundfünfzig").
transcribe_number(de, nominative, 60, "sechzig").
transcribe_number(de, nominative, 61, "einundsechzig").
transcribe_number(de, nominative, 62, "zweiundsechzig").
transcribe_number(de, nominative, 63, "dreiundsechzig").
transcribe_number(de, nominative, 64, "vierundsechzig").
transcribe_number(de, nominative, 65, "fünfundsechzig").
transcribe_number(de, nominative, 66, "sechsundsechzig").
transcribe_number(de, nominative, 67, "siebenundsechzig").
transcribe_number(de, nominative, 68, "achtundsechzig").
transcribe_number(de, nominative, 69, "neunundsechzig").
transcribe_number(de, nominative, 70, "siebzig").
transcribe_number(de, nominative, 71, "einundsiebzig").
transcribe_number(de, nominative, 72, "zweiundsiebzig").
transcribe_number(de, nominative, 73, "dreiundsiebzig").
transcribe_number(de, nominative, 74, "vierundsiebzig").
transcribe_number(de, nominative, 75, "fünfundsiebzig").
transcribe_number(de, nominative, 76, "sechsundsiebzig").
transcribe_number(de, nominative, 77, "siebenundsiebzig").
transcribe_number(de, nominative, 78, "achtundsiebzig").
transcribe_number(de, nominative, 79, "neunundsiebzig").
transcribe_number(de, nominative, 80, "achtzig").
transcribe_number(de, nominative, 81, "einundachtzig").
transcribe_number(de, nominative, 82, "zweiundachtzig").
transcribe_number(de, nominative, 83, "dreiundachtzig").
transcribe_number(de, nominative, 84, "vierundachtzig").
transcribe_number(de, nominative, 85, "fünfundachtzig").
transcribe_number(de, nominative, 86, "sechsundachtzig").
transcribe_number(de, nominative, 87, "siebenundachtzig").
transcribe_number(de, nominative, 88, "achtundachtzig").
transcribe_number(de, nominative, 89, "neunundachtzig").
transcribe_number(de, nominative, 90, "neunzig").
transcribe_number(de, nominative, 91, "einundneunzig").
transcribe_number(de, nominative, 92, "zweiundneunzig").
transcribe_number(de, nominative, 93, "dreiundneunzig").
transcribe_number(de, nominative, 94, "vierundneunzig").
transcribe_number(de, nominative, 95, "fünfundneunzig").
transcribe_number(de, nominative, 96, "sechsundneunzig").
transcribe_number(de, nominative, 97, "siebenundneunzig").
transcribe_number(de, nominative, 98, "achtundneunzig").
transcribe_number(de, nominative, 99, "neunundneunzig").
transcribe_number(de, nominative, 100, "hundert").


transcribe_number(de, ord_nom,  0, "nullte").
transcribe_number(de, ord_nom,  1, "erste").
transcribe_number(de, ord_nom,  2, "zweite").
transcribe_number(de, ord_nom,  3, "dritte").
transcribe_number(de, ord_nom,  4, "vierte").
transcribe_number(de, ord_nom,  5, "fünfte").
transcribe_number(de, ord_nom,  6, "sechste").
transcribe_number(de, ord_nom,  7, "siebte").
transcribe_number(de, ord_nom,  8, "achte").
transcribe_number(de, ord_nom,  9, "neunte").
transcribe_number(de, ord_nom, 10, "zehnte").
transcribe_number(de, ord_nom, 11, "elfte").
transcribe_number(de, ord_nom, 12, "zwölfte").
transcribe_number(de, ord_nom, 13, "dreizehnte").
transcribe_number(de, ord_nom, 14, "vierzehnte").
transcribe_number(de, ord_nom, 15, "fünfzehnte").
transcribe_number(de, ord_nom, 16, "sechzehnte").
transcribe_number(de, ord_nom, 17, "siebzehnte").
transcribe_number(de, ord_nom, 18, "achtzehnte").
transcribe_number(de, ord_nom, 19, "neunzehnte").
transcribe_number(de, ord_nom, 20, "zwanzigste").
transcribe_number(de, ord_nom, 21, "einundzwanzigste").
transcribe_number(de, ord_nom, 22, "zweiundzwanzigste").
transcribe_number(de, ord_nom, 23, "dreiundzwanzigste").
transcribe_number(de, ord_nom, 24, "vierundzwanzigste").
transcribe_number(de, ord_nom, 25, "fünfundzwanzigste").
transcribe_number(de, ord_nom, 26, "sechsundzwanzigste").
transcribe_number(de, ord_nom, 27, "siebenundzwanzigste").
transcribe_number(de, ord_nom, 28, "achtundzwanzigste").
transcribe_number(de, ord_nom, 29, "neunundzwanzigste").
transcribe_number(de, ord_nom, 30, "dreißigste").
transcribe_number(de, ord_nom, 31, "einunddreißigste").
transcribe_number(de, ord_nom, 32, "zweiunddreißigste").
transcribe_number(de, ord_nom, 33, "dreiunddreißigste").
transcribe_number(de, ord_nom, 34, "vierunddreißigste").
transcribe_number(de, ord_nom, 35, "fünfunddreißigste").
transcribe_number(de, ord_nom, 36, "sechsunddreißigste").
transcribe_number(de, ord_nom, 37, "siebenunddreißigste").
transcribe_number(de, ord_nom, 38, "achtunddreißigste").
transcribe_number(de, ord_nom, 39, "neununddreißigste").
transcribe_number(de, ord_nom, 40, "vierzigste").
transcribe_number(de, ord_nom, 41, "einundvierzigste").
transcribe_number(de, ord_nom, 42, "zweiundvierzigste").
transcribe_number(de, ord_nom, 43, "dreiundvierzigste").
transcribe_number(de, ord_nom, 44, "vierundvierzigste").
transcribe_number(de, ord_nom, 45, "fünfundvierzigste").
transcribe_number(de, ord_nom, 46, "sechsundvierzigste").
transcribe_number(de, ord_nom, 47, "siebenundvierzigste").
transcribe_number(de, ord_nom, 48, "achtundvierzigste").
transcribe_number(de, ord_nom, 49, "neunundvierzigste").
transcribe_number(de, ord_nom, 50, "fünfzigste").
transcribe_number(de, ord_nom, 51, "einundfünfzigste").
transcribe_number(de, ord_nom, 52, "zweiundfünfzigste").
transcribe_number(de, ord_nom, 53, "dreiundfünfzigste").
transcribe_number(de, ord_nom, 54, "vierundfünfzigste").
transcribe_number(de, ord_nom, 55, "fünfundfünfzigste").
transcribe_number(de, ord_nom, 56, "sechsundfünfzigste").
transcribe_number(de, ord_nom, 57, "siebenundfünfzigste").
transcribe_number(de, ord_nom, 58, "achtundfünfzigste").
transcribe_number(de, ord_nom, 59, "neunundfünfzigste").
transcribe_number(de, ord_nom, 60, "sechzigste").
transcribe_number(de, ord_nom, 61, "einundsechzigste").
transcribe_number(de, ord_nom, 62, "zweiundsechzigste").
transcribe_number(de, ord_nom, 63, "dreiundsechzigste").
transcribe_number(de, ord_nom, 64, "vierundsechzigste").
transcribe_number(de, ord_nom, 65, "fünfundsechzigste").
transcribe_number(de, ord_nom, 66, "sechsundsechzigste").
transcribe_number(de, ord_nom, 67, "siebenundsechzigste").
transcribe_number(de, ord_nom, 68, "achtundsechzigste").
transcribe_number(de, ord_nom, 69, "neunundsechzigste").
transcribe_number(de, ord_nom, 70, "siebzigste").
transcribe_number(de, ord_nom, 71, "einundsiebzigste").
transcribe_number(de, ord_nom, 72, "zweiundsiebzigste").
transcribe_number(de, ord_nom, 73, "dreiundsiebzigste").
transcribe_number(de, ord_nom, 74, "vierundsiebzigste").
transcribe_number(de, ord_nom, 75, "fünfundsiebzigste").
transcribe_number(de, ord_nom, 76, "sechsundsiebzigste").
transcribe_number(de, ord_nom, 77, "siebenundsiebzigste").
transcribe_number(de, ord_nom, 78, "achtundsiebzigste").
transcribe_number(de, ord_nom, 79, "neunundsiebzigste").
transcribe_number(de, ord_nom, 80, "achtzigste").
transcribe_number(de, ord_nom, 81, "einundachtzigste").
transcribe_number(de, ord_nom, 82, "zweiundachtzigste").
transcribe_number(de, ord_nom, 83, "dreiundachtzigste").
transcribe_number(de, ord_nom, 84, "vierundachtzigste").
transcribe_number(de, ord_nom, 85, "fünfundachtzigste").
transcribe_number(de, ord_nom, 86, "sechsundachtzigste").
transcribe_number(de, ord_nom, 87, "siebenundachtzigste").
transcribe_number(de, ord_nom, 88, "achtundachtzigste").
transcribe_number(de, ord_nom, 89, "neunundachtzigste").
transcribe_number(de, ord_nom, 90, "neunzigste").
transcribe_number(de, ord_nom, 91, "einundneunzigste").
transcribe_number(de, ord_nom, 92, "zweiundneunzigste").
transcribe_number(de, ord_nom, 93, "dreiundneunzigste").
transcribe_number(de, ord_nom, 94, "vierundneunzigste").
transcribe_number(de, ord_nom, 95, "fünfundneunzigste").
transcribe_number(de, ord_nom, 96, "sechsundneunzigste").
transcribe_number(de, ord_nom, 97, "siebenundneunzigste").
transcribe_number(de, ord_nom, 98, "achtundneunzigste").
transcribe_number(de, ord_nom, 99, "neunundneunzigste").
transcribe_number(de, ord_nom, 100, "hundertste").

transcribe_number(de, ord_gen,  0, "nullten").
transcribe_number(de, ord_gen,  1, "ersten").
transcribe_number(de, ord_gen,  2, "zweiten").
transcribe_number(de, ord_gen,  3, "dritten").
transcribe_number(de, ord_gen,  4, "vierten").
transcribe_number(de, ord_gen,  5, "fünften").
transcribe_number(de, ord_gen,  6, "sechsten").
transcribe_number(de, ord_gen,  7, "siebten").
transcribe_number(de, ord_gen,  8, "achten").
transcribe_number(de, ord_gen,  9, "neunten").
transcribe_number(de, ord_gen, 10, "zehnten").
transcribe_number(de, ord_gen, 11, "elften").
transcribe_number(de, ord_gen, 12, "zwölften").
transcribe_number(de, ord_gen, 13, "dreizehnten").
transcribe_number(de, ord_gen, 14, "vierzehnten").
transcribe_number(de, ord_gen, 15, "fünfzehnten").
transcribe_number(de, ord_gen, 16, "sechzehnten").
transcribe_number(de, ord_gen, 17, "siebzehnten").
transcribe_number(de, ord_gen, 18, "achtzehnten").
transcribe_number(de, ord_gen, 19, "neunzehnten").
transcribe_number(de, ord_gen, 20, "zwanzigsten").
transcribe_number(de, ord_gen, 21, "einundzwanzigsten").
transcribe_number(de, ord_gen, 22, "zweiundzwanzigsten").
transcribe_number(de, ord_gen, 23, "dreiundzwanzigsten").
transcribe_number(de, ord_gen, 24, "vierundzwanzigsten").
transcribe_number(de, ord_gen, 25, "fünfundzwanzigsten").
transcribe_number(de, ord_gen, 26, "sechsundzwanzigsten").
transcribe_number(de, ord_gen, 27, "siebenundzwanzigsten").
transcribe_number(de, ord_gen, 28, "achtundzwanzigsten").
transcribe_number(de, ord_gen, 29, "neunundzwanzigsten").
transcribe_number(de, ord_gen, 30, "dreißigsten").
transcribe_number(de, ord_gen, 31, "einunddreißigsten").
transcribe_number(de, ord_gen, 32, "zweiunddreißigsten").
transcribe_number(de, ord_gen, 33, "dreiunddreißigsten").
transcribe_number(de, ord_gen, 34, "vierunddreißigsten").
transcribe_number(de, ord_gen, 35, "fünfunddreißigsten").
transcribe_number(de, ord_gen, 36, "sechsunddreißigsten").
transcribe_number(de, ord_gen, 37, "siebenunddreißigsten").
transcribe_number(de, ord_gen, 38, "achtunddreißigsten").
transcribe_number(de, ord_gen, 39, "neununddreißigsten").
transcribe_number(de, ord_gen, 40, "vierzigsten").
transcribe_number(de, ord_gen, 41, "einundvierzigsten").
transcribe_number(de, ord_gen, 42, "zweiundvierzigsten").
transcribe_number(de, ord_gen, 43, "dreiundvierzigsten").
transcribe_number(de, ord_gen, 44, "vierundvierzigsten").
transcribe_number(de, ord_gen, 45, "fünfundvierzigsten").
transcribe_number(de, ord_gen, 46, "sechsundvierzigsten").
transcribe_number(de, ord_gen, 47, "siebenundvierzigsten").
transcribe_number(de, ord_gen, 48, "achtundvierzigsten").
transcribe_number(de, ord_gen, 49, "neunundvierzigsten").
transcribe_number(de, ord_gen, 50, "fünfzigsten").
transcribe_number(de, ord_gen, 51, "einundfünfzigsten").
transcribe_number(de, ord_gen, 52, "zweiundfünfzigsten").
transcribe_number(de, ord_gen, 53, "dreiundfünfzigsten").
transcribe_number(de, ord_gen, 54, "vierundfünfzigsten").
transcribe_number(de, ord_gen, 55, "fünfundfünfzigsten").
transcribe_number(de, ord_gen, 56, "sechsundfünfzigsten").
transcribe_number(de, ord_gen, 57, "siebenundfünfzigsten").
transcribe_number(de, ord_gen, 58, "achtundfünfzigsten").
transcribe_number(de, ord_gen, 59, "neunundfünfzigsten").
transcribe_number(de, ord_gen, 60, "sechzigsten").
transcribe_number(de, ord_gen, 61, "einundsechzigsten").
transcribe_number(de, ord_gen, 62, "zweiundsechzigsten").
transcribe_number(de, ord_gen, 63, "dreiundsechzigsten").
transcribe_number(de, ord_gen, 64, "vierundsechzigsten").
transcribe_number(de, ord_gen, 65, "fünfundsechzigsten").
transcribe_number(de, ord_gen, 66, "sechsundsechzigsten").
transcribe_number(de, ord_gen, 67, "siebenundsechzigsten").
transcribe_number(de, ord_gen, 68, "achtundsechzigsten").
transcribe_number(de, ord_gen, 69, "neunundsechzigsten").
transcribe_number(de, ord_gen, 70, "siebzigsten").
transcribe_number(de, ord_gen, 71, "einundsiebzigsten").
transcribe_number(de, ord_gen, 72, "zweiundsiebzigsten").
transcribe_number(de, ord_gen, 73, "dreiundsiebzigsten").
transcribe_number(de, ord_gen, 74, "vierundsiebzigsten").
transcribe_number(de, ord_gen, 75, "fünfundsiebzigsten").
transcribe_number(de, ord_gen, 76, "sechsundsiebzigsten").
transcribe_number(de, ord_gen, 77, "siebenundsiebzigsten").
transcribe_number(de, ord_gen, 78, "achtundsiebzigsten").
transcribe_number(de, ord_gen, 79, "neunundsiebzigsten").
transcribe_number(de, ord_gen, 80, "achtzigsten").
transcribe_number(de, ord_gen, 81, "einundachtzigsten").
transcribe_number(de, ord_gen, 82, "zweiundachtzigsten").
transcribe_number(de, ord_gen, 83, "dreiundachtzigsten").
transcribe_number(de, ord_gen, 84, "vierundachtzigsten").
transcribe_number(de, ord_gen, 85, "fünfundachtzigsten").
transcribe_number(de, ord_gen, 86, "sechsundachtzigsten").
transcribe_number(de, ord_gen, 87, "siebenundachtzigsten").
transcribe_number(de, ord_gen, 88, "achtundachtzigsten").
transcribe_number(de, ord_gen, 89, "neunundachtzigsten").
transcribe_number(de, ord_gen, 90, "neunzigsten").
transcribe_number(de, ord_gen, 91, "einundneunzigsten").
transcribe_number(de, ord_gen, 92, "zweiundneunzigsten").
transcribe_number(de, ord_gen, 93, "dreiundneunzigsten").
transcribe_number(de, ord_gen, 94, "vierundneunzigsten").
transcribe_number(de, ord_gen, 95, "fünfundneunzigsten").
transcribe_number(de, ord_gen, 96, "sechsundneunzigsten").
transcribe_number(de, ord_gen, 97, "siebenundneunzigsten").
transcribe_number(de, ord_gen, 98, "achtundneunzigsten").
transcribe_number(de, ord_gen, 99, "neunundneunzigsten").
transcribe_number(de, ord_gen, 100, "hundertsten").

