Guide to ZamiaAI Prolog
=======================
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

Context
-------

[source,prolog]
------------------------------------------------------------
C:context|topic := wdePolitics
------------------------------------------------------------

Memory
------

[source,prolog]
------------------------------------------------------------
C:mem|f1ent := HUMAN
------------------------------------------------------------

set memory entry to entity and later retrieve entities label:

[source,prolog]
------------------------------------------------------------
C:mem|f1ent := wdeStuttgart
[...]
"{C:mem|f1ent:rdfsLabel|en, s}"
------------------------------------------------------------

User
----
[source,prolog]
------------------------------------------------------------
train(en) :-
    "(do you remember my name|what was my name|what is my name|do you know my name)?",
    if nonvar(C:user:name) then
        "Your name is {C:user:name, s}"
    else
        or ("I don't think you ever told me your name?",
            "Did you ever tell me your name?")
    endif.
------------------------------------------------------------

Self
----
[source,prolog]
------------------------------------------------------------
   or ( "I am called {self:rdfsLabel|en, s}",
         "My name is {self:rdfsLabel|en, s}").
------------------------------------------------------------

Training Data
-------------

Patterns used in input, multiple answers in response:

[source,prolog]
------------------------------------------------------------
train(en) :-
   "what are you called (by the way|again|)?",
   or ( "I am called {self:rdfsLabel|en, s}",
         "My name is {self:rdfsLabel|en, s}").
------------------------------------------------------------

you can also have multiple input patterns:
[source,prolog]
------------------------------------------------------------
train(en) :-
   or ( "what are you called (by the way|again|)?",
        "what is your name (by the way|again|)?" ),
   or ( "I am called {self:rdfsLabel|en, s}",
         "My name is {self:rdfsLabel|en, s}").
------------------------------------------------------------

limit training data to a specific contexts:
[source,prolog]
------------------------------------------------------------
train(en) :-
    context(topic, wdeProgrammingLanguage),
    'I like prolog',
    'That is a nice programming language'.
------------------------------------------------------------

or multiple different contexts:
[source,prolog]
------------------------------------------------------------
train(en) :-
    or (context(topic, wdeComputer), context(topic, wdeProgrammingLanguage), true),
    'I like prolog',
    'That is a nice programming language'.
------------------------------------------------------------

Scoring
-------

[source,prolog]
------------------------------------------------------------
r_score(C, 200.0)
------------------------------------------------------------

