Guide to ZamiaAI Frame Semantics
================================

Semantic Processing Flow Overview
---------------------------------

[ditaa,"general_flow"]
....

+-------------------------+   
| Layer1                  |  happens outside of prolog engine
|                         |
| iasN assertions         |  e.g. ias(ias1, tokens, ["do", "you", "know", "obama"])
+-------------------------+
            |
            |
            v
+-------------------------+
| Layer2                  |
|                         |
| utterance frame graph   |
+-------------------------+
            |
            |
            v
+-------------------------+
| Layer3                  |
|                         |
| response frame graph(s) |
+-------------------------+
            |
            |
            v
+-------------------------+
| Layer4                  |
|                         |
| actions                 |
+-------------------------+
....

General Notes
-------------

- ZamiaAI's semantic frames are heavily based on FrameNet vocabulary but deviate and extend where it seems appropriate
- ZamiaAI uses frames to try to represent the full semantics of uttterances and responses, so ZamiaAI frames form a true
  abstraction layer separating the semantic processing from the natural language input/output layer
- each utterance is represented as a unique prolog atom iasN representing the current utterance processing step

Layer 1: iasN Assertions Environment
------------------------------------

The outer framework will put iasN assertions representing information about the current utterance
to be processed into the prolog environment before invoking the prolog runtime. 

Example:

[source,prolog]
ias(ias1, user,        aiu:Alice)
ias(ias1, utterance,   "do you know obama")
ias(ias1, uttLang,     en)
ias(ias1, tokens,      ["do", "you", "know", "obama"]
ias(ias1, currentTime, "2017-05-06T18:20:43+00:00")
ias(ias1, prevIAS,     ias0)

Layer 2: Generate Utterance Frame Graph
---------------------------------------

Layer 2 processing typicalle generates an utterance frame graph using the FrameNet virtual machine (FNVM) 
and named entity recognition (NER).

The frame graph is constructed by setting up a list VMC of FNVM commands and then invoking

[source,prolog]
    fnvm_exec (en, I, VMC)

on it, which in turn will create the graph and run a search on it:

[source,prolog]
    l3proc (LANG, I, frame2, fnQuestioning)

Example input: 'do you know obama'

[source,prolog]
------------------------------------------------------------
    exp_ner(en, I, NER1CLASS, 4, 5, NER1ENTITY),

    list_append(VMC, fe(ent, NER1ENTITY)),
    list_append(VMC, fe(entclass, NER1CLASS)),
    list_append(VMC, fe(cog, uriref(aiu:self))),
    list_append(VMC, frame(fnFamiliarity)),
    
    list_append(VMC, fe(msg,  vm_frame_pop)),
    list_append(VMC, fe(top,  existance)),
    list_append(VMC, fe(add,  uriref(aiu:self))),
    ias(I, user, USER),
    list_append(VMC, fe(spkr, USER)),
    list_append(VMC, frame(fnQuestioning)),
    
    fnvm_exec (en, I, VMC)
------------------------------------------------------------

will generate a frame graph like this:

[ditaa, "uframe_graph"]
....
+---------------------+
| frame2              |
|                     |
| type  fnQuestioning |
| top   existance     |
| add   aiu self      |
| msg   frame1  ------|--------------+
+---------------------+              |
                                     v
                        +---------------------------+
                        | frame1                    |
                        |                           |
                        | type      fnFamiliarity   |
                        | ent       woe Q76         |
                        | entclass  woe human       |
                        | cog       aiu self        |
                        +---------------------------+
....

Example input 'when was he born'

[source,prolog]
------------------------------------------------------------
    list_append(VMC, frame(fnBeingBorn)),
    
    list_append(VMC, fe(msg, vm_pop_frame))
    list_append(VMC, fe(topic, time)),
    list_append(VMC, fe(addressee, uriref(aiu:self))),
    list_append(VMC, frame(fnQuestioning)),
    
    fnvm_exec (en, I, VMC)
------------------------------------------------------------

Example input 'and where'

[source,prolog]
------------------------------------------------------------
    list_append(VMC, fe(topic, place)),
    list_append(VMC, fe(addressee, uriref(aiu:self))),
    list_append(VMC, frame(fnQuestioning)),
    
    fnvm_exec (en, I, VMC)
------------------------------------------------------------


Layer 3: Thought process
------------------------

In this layer the deeper thought process happens. This starts by processing the 
utterance frame graph and (hopefully) ends in the generation of appropriate
response frame graph(s).

- filling in missing utterance frame slots (fill_blanks) using information from
  - previous frames
  - RDF triples

- storing the completed utterance frame as uframe in ias:
  assertz(ias(I, uframe, F))

- producing one or more response frame graphs, e.g.

[source,prolog]
------------------------------------------------------------
    list_append(VMC, fe(msg,  MSGF)),
    list_append(VMC, fe(top,  existance)),
    list_append(VMC, fe(act,  affirm)),
    frame (F, spkr, USER),
    list_append(VMC, fe(add,  USER)),
    list_append(VMC, fe(spkr, uriref(aiu:self))),
    list_append(VMC, frame(fnAffirmOrDeny)),

    fnvm_graph(VMC, RFRAME)
------------------------------------------------------------

this can happen inside the predicate or by invoking other l3proc predicates on the completed uframe

- storing the completed response frame(s) as rframe in ias:
  assertz(ias(I, rframe, RFRAME))

- invoking layer 4 for adding actions appropriate to the response frame(s):
  l4proc (LANG, I)

NOTE: both uframe and rframe generation are typically ambigous, as are all NLP tasks. so score points
      should be added as appropriate during processing so the outer framework can act the/one of the best
      response(s)
  
Layer 4: Add Response Actions
-----------------------------

In this layer actions are added to the iasN structure which are (hopefully) appropriate to the response
frame(s) generated in the previous layer. Typically, these actions will contain utterances represented
by say() actions asserted.

Example response frame graph: 

[ditaa, "rframe_graph"]
....
+---------------------+
| frame4              |
|                     |
| type  fnTelling     |
| top   place         |
| msg   frame3  ------|--------------+
+---------------------+              |
                                     v
                        +---------------------------+
                        | frame3                    |
                        |                           |
                        | type      fnBeingBorn     |
                        | child     woe Q76         |
                        | place     woe Q6366688    |
                        +---------------------------+
....

Example prolog code for response action generation:

[source,prolog]
------------------------------------------------------------
    answerz (I, en, personBeenBornWhere, LABEL, BP_LABEL, GENDER) :- 
        sayz(I, en, format_str("%s was born in %s", LABEL, BP_LABEL)).
    answerz (I, en, personBeenBornWhere, LABEL, BP_LABEL, male)   :- 
        sayz(I, en, format_str("he was born in %s", BP_LABEL)).
    answerz (I, en, personBeenBornWhere, LABEL, BP_LABEL, female) :- 
        sayz(I, en, format_str("she was born in %s", BP_LABEL)).
    
    l4proc (LANG, I, F, fnTelling, place, MSGF, fnBeingBorn) :-
    
        frame (MSGF, child, PERSON),
        frame (MSGF, place, BP),    
    
        person_gender(PERSON, GENDER),
    
        entity_label(LANG, PERSON, LABEL),
        entity_label(LANG, BP, BP_LABEL),
    
        answerz (I, LANG, personBeenBornWhere, LABEL, BP_LABEL, GENDER).
------------------------------------------------------------
